import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Heart, MessageCircle, Code2, Globe2, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { story } from '@/lib/story';

export function StoryTimeline() {
  const chapters = [
    ['01', '10 SEPTEMBER 2025', 'Ek message. Ek nayi duniya.', 'Hum Facebook par mile thay. Ek aam si mulaqat dheere dheere meri zindagi ki sab se khaas kahani ban gayi. Hum ek doosre par jaan waarte thay.'],
    ['02', 'SARDAR SE SHAH TAK', 'Tumne mujhe ek naya naam diya.', 'Duniya mujhe Sardar RDX ke naam se jaanti thi. Tumne mujhe Shah kaha — aur phir main isi naam se mashhoor ho gaya. Mere naam mein bhi tumhari yaad bas gayi.'],
    ['03', 'EK SAAL, BESHUMAAR YAADEN', 'Mushkil waqt. Wohi mohabbat.', 'Humne bohat si mushkilaat ka saamna kiya, lekin kabhi alag nahi hue. Ek saal mein hum ek doosre ki aadat ban gaye. Mere bohat dost thay, magar maine apna waqt tumhein diya. Doston ke replies chhor diye, kyun ke tum meri jaan, meri mohabbat thi.'],
    ['04', '3 OCTOBER 2026 · 8:36 PM', 'Aakhri message. Adhoori baat.', 'Us raat tumhara aakhri message aaya. Ek ghalat fehmi ne hamare darmiyan khamoshi la di. Main apni ghalti ke liye dil se maafi maangta hoon. Tum aaj bhi mere liye sab se azeez ho.'],
  ];
  return <div className="timeline">{chapters.map(([number, date, title, text]) => <article className="timeline-item reveal" key={number}><div className="chapter-number">{number}</div><div><p className="eyebrow">{date}</p><h3>{title}</h3><p>{text}</p></div><Heart className="timeline-heart" size={15} /></article>)}</div>;
}
export function Letter({ full = false }: { full?: boolean }) {
  return <section className="letter-section reveal"><div className="section-kicker"><span /> DIL SE, SIRF TUMHARE LIYE <span /></div><Heart className="letter-heart" size={27} strokeWidth={1} /><h2>Mano, <em>mujhe maaf kar do.</em></h2><div className="letter-copy"><p>Mano, mujhe tumse zyada azeez koi nahi. Jo ghalat fehmi hamare darmiyan aayi, us ke liye main dil se maafi maangta hoon. Main apni ghalti ki maafi chahta hoon.</p>{full && <><p>10 September 2025 ko hum mile thay. Tumne mujhe Shah ka naam diya, aur meri duniya badal gayi. Humne mushkilaat saath dekheen; tum meri aadat, meri jaan aur meri sab se khaas mohabbat ban gayi.</p><p>3 October 2026, raat 8:36 par tumhara aakhri message aaya. Us ke baad ki khamoshi mein bhi meri mohabbat kam nahi hui. Main tumhari baat sunna chahta hoon, aur apni ghalti ko samajh kar behtar banna chahta hoon.</p></>}<p>Main aaj bhi tumhare intezaar mein hoon. Tumhare baghair rehna mere liye bohat mushkil hai. Please, mujhe maaf kar do. Agar tumhara dil chahe, wapis aa jao.</p>{full && <p>Tumhare jazbaat aur tumhari marzi mere liye aham hain. Jab tum tayyar ho, main yahin hoon — tumhari baat sunne ke liye.</p>}</div><p className="signature">Tumhara, Shah <span>♡</span></p><Button asChild className="rose-button"><a href={story.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle /> Baat kar lo, Mano <ArrowUpRight /></a></Button>{!full && <Link to="/for-mano" className="text-link">Read the whole letter <ArrowUpRight size={14} /></Link>}</section>;
}
export function BotFeature({ full = false }: { full?: boolean }) {
  return <section className="bot-section reveal"><div><p className="eyebrow">HER NAME. MY CREATION.</p><h2>Code mein bhi,<br /><em>tum hi ho.</em></h2><p>Main Pakistan ka programmer aur vibe coder hoon. Messenger aur WhatsApp ke liye maine jo bot banaya, uska naam bhi tum par rakha — <strong>Mano Bot.</strong></p>{full && <p>Mere liye yeh sirf code nahi. Yeh meri mehnat aur tumhare naam se judi ek yaad hai. Mere mutabiq, 10 mukhtalif countries ke log isay chalate aur pasand karte hain. Jahan Mano Bot dikhta hai, log usay Sardar RDX ki creation ke taur par pehchante hain.</p>}<Button asChild variant="outline"><Link to={full ? '/our-story' : '/mano-bot'}>{full ? 'The story behind the name' : 'Meet Mano Bot'} <ArrowUpRight /></Link></Button></div><div className="bot-art"><div className="bot-symbol"><Code2 size={48} strokeWidth={1} /><Heart size={21} /></div><span className="bot-label">MANO BOT</span><span className="bot-byline">BUILT BY SARDAR RDX · NAMED WITH LOVE</span><div className="bot-stats"><span><Globe2 size={16} /> 10 countries</span><span><Sparkles size={16} /> One inspiration</span></div><p>Messenger <span>·</span> WhatsApp</p></div></section>;
}