/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForManoRouteImport } from './routes/for-mano'
import { Route as ManoBotRouteImport } from './routes/mano-bot'
import { Route as OurStoryRouteImport } from './routes/our-story'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForManoRoute = ForManoRouteImport.update({
  id: '/for-mano',
  path: '/for-mano',
  getParentRoute: () => rootRouteImport,
} as any)
const ManoBotRoute = ManoBotRouteImport.update({
  id: '/mano-bot',
  path: '/mano-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-mano': typeof ForManoRoute
  '/mano-bot': typeof ManoBotRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-mano': typeof ForManoRoute
  '/mano-bot': typeof ManoBotRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-mano': typeof ForManoRoute
  '/mano-bot': typeof ManoBotRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/for-mano' | '/mano-bot' | '/our-story'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/for-mano' | '/mano-bot' | '/our-story'
  id: '__root__' | '/' | '/for-mano' | '/mano-bot' | '/our-story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForManoRoute: typeof ForManoRoute
  ManoBotRoute: typeof ManoBotRoute
  OurStoryRoute: typeof OurStoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-mano': {
      id: '/for-mano'
      path: '/for-mano'
      fullPath: '/for-mano'
      preLoaderRoute: typeof ForManoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mano-bot': {
      id: '/mano-bot'
      path: '/mano-bot'
      fullPath: '/mano-bot'
      preLoaderRoute: typeof ManoBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForManoRoute: ForManoRoute,
  ManoBotRoute: ManoBotRoute,
  OurStoryRoute: OurStoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
